apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bluetron-financial-finalizer
  name: bluetron-financial-finalizer
  namespace: bluetron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluetron-financial-finalizer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bluetron-financial-finalizer
    spec:
      volumes:
      - name: hostvolume
        persistentVolumeClaim:
          claimName: local-hostpath-pvc
      containers:
      - image: bluetron/hackathon:financialfinalizer
        name: financialfinalizer
        volumeMounts:
        - name: hostvolume
          mountPath: /mnt/data
        resources: {}
        env:
        - name: BLUETRON_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: bluetron-admin-token-xc28r
        - name: BLUETRON_CERT
          valueFrom:
            secretKeyRef:
              key: ca.crt
              name: bluetron-admin-token-xc28r
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bluetron-financial-finalizer
  name: bluetron-financial-finalizer
  namespace: bluetron
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: bluetron-financial-finalizer
  sessionAffinity: None
  type: ClusterIP
