apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: sample
  namespace: bluetron
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: bluetron-admin
  namespace: bluetron
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - metrics.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - argoproj.io
  resources:
  - '*'
  verbs:
  - '*'
---
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: bluetron-admin
  namespace: bluetron
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bluetron-admin
subjects:
- kind: ServiceAccount
  name: bluetron-admin
  namespace: bluetron
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bluetron-financial-processor
  name: bluetron-financial-processor
  namespace: bluetron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluetron-financial-processor
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bluetron-financial-processor
    spec:
      volumes: 
      - name: hostvolume
        persistentVolumeClaim:
          claimName: local-hostpath-pvc
      containers:
      - image: bluetron/hackathon:financialprocessor
        name: financialprocessor
        volumeMounts:
        - name: hostvolume
          mountPath: /mnt/data
        resources: {}
        env:
        - name: BLUETRON_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: $(nameOfSecret)
        - name: BLUETRON_CERT
          valueFrom:
            secretKeyRef:
              key: ca.crt
              name: $(nameOfSecret)
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bluetron-financial-processor
  name: bluetron-financial-processor
  namespace: bluetron
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: bluetron-financial-processor
  sessionAffinity: None
  type: ClusterIP
